appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tEJEbH8sahv6POmJBCrYtR+cdaq6Z5qSkAPHCD7XQ0VFyubvF4HYfGl79aa8iAbQJuRNtpBrFXtjRJDNc2RuPTaG5okvFLndtD87Hq9ryXipGDdDQ9Z0TL5Uwhct44aPUl3bBFCq4VGBaUQebq+DbQL1RCQ17WoJOMAB650kK3rlWdt3+tPTiHerYXrAn3eGkoOreAT4u7dEjiEMJIbJaxeXmGs4ts6RVN5+Zbyd3H1jsbuyMQkgSyEsDlshbLMLAX1IKXR20mgeLdlDOl4BRT26VlYBlsIhbTM9GUVErClgOBDr/xFLqTTsQyV0jdK4Cit5HGOH9J9Xdvcq+FgXOGRXSwOSkR7cIL8wabGf81W13EHcDab5Sp3fNbST8lkRJCY1lBCnZbFn/WQbYUnLbOSgqiytSIenfG8avMIs1ScXHeMv0cLTSKiUyzgUMUo6pL/IR/HQpVJ0DHmjTl+HdwlsxEUm+i3n7QxV1NmfKlCI+kRdnNcSvNz2zU8Pbydfcin+MHcgeScpO0e6bE5HVvhLqZNVzBZbKn79iKcJ64T7TLgIMv7w1lTBwsyuRoQSBEv8bgy9H/AJ9m+hRgPbwdywJqg2gcIWVzmQB1f7QnjRtnF/H1zOsRJz3ZG9FuKshH5CHX5l96yxDDJM8XkQr26yuf/pfu0m7sVI8I7NpME=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
